[versions]
agp = "8.5.0"
kotlin = "1.9.0"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.6.1"
activityCompose = "1.8.0"
composeBom = "2024.04.01"
timber = "5.0.1"
retrofit = "2.11.0"
okhttp = "4.11.0"
moshiConv = "2.11.0"
moshi = "1.15.2"
moshiKotlinCodegen = "1.15.2"
ksp = "1.9.0-1.0.12"
lifecycle-viewmodel-compose = "2.8.7"
secretsGradlePlugin = "2.0.1"
composeNavigation = "2.8.0-alpha08"
serialization = "1.6.3"
coil-compose = "3.0.4"
coil-network-okhttp = "3.0.4"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

#navigation

navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization"}

#API management
retrofit = {module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit"}
moshiConv = {module = "com.squareup.retrofit2:converter-moshi", version.ref = "moshiConv"}
okhttp = {module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp"}
moshi = {module = "com.squareup.moshi:moshi", version.ref = "moshi"}
moshiCodegen = {module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshiKotlinCodegen"}
moshiAdapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi" }
moshiKotlinReflect = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel-compose" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil-compose" }
coil-network-okhttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil-network-okhttp" }



[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
secrets-gradle = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secretsGradlePlugin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
